"""upgrade password2

Revision ID: 6dd111c76480
Revises: 5cff5f117d8b
Create Date: 2021-07-11 23:09:12.771388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd111c76480'
down_revision = '5cff5f117d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password2', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password2')
    # ### end Alembic commands ###
